---
- name: Playbook to install Mac Applications
  hosts: localhost
  connection: local

  vars:
    apps:
      - name: "Microsoft Word"
        id: "462054704"
      - name: "Microsoft Outlook"
        id: "985367838"
      - name: "Microsoft OneNote"
        id: "784801555"
      - name: "Microsoft Excel"
        id: "462058435"
      - name: "Microsoft PowerPoint"
        id: "462062816"
      - name: "Microsoft Remote Desktop"
        id: "1295203466"
      - name: "Microsoft To Do"
        id: "1274495053"
      - name: "OneDrive"
        id: "823766827"
      - name: "LastPass Password Manager"
        id: "926036361"
      - name: "PDF to Word Free"
        id: "956036306"

  tasks:
    - name: Install All desired Apps using Apple Store CLI
      block:
        - name: Install App using mas module
          community.general.mas:
            id: "{{ item.id }}"
            state: present
          loop: "{{ apps }}"
      rescue:
        - name: Install using the mas command line
          command: mas purchase "{{ item.id }}"
          register: mas_result
          loop: "{{ apps }}"
          changed_when: '"Warning:" not in mas_result.stdout'

    - name: Upgrade All installed apps to the latest version
      community.general.mas:
        upgrade_all: true
